import os
from dotenv import load_dotenv
from supabase import create_client, Client

load_dotenv()

SUPABASE_URL = "https://dyjcskzwgztfzrafefxa.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5amNza3p3Z3p0ZnpyYWZlZnhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM5MTI2ODIsImV4cCI6MjA3OTQ4ODY4Mn0.h24P81bLHQaRDOvSwsRT6c9GiYzfpYcSe6D4xmzLpdc"

supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)

# SQL to create users table
# Note: In a real app we'd use Supabase Auth, but for this custom requirement we'll use a table.
# We'll use a simple text password for this demo as requested (no backend hashing available easily without edge functions).
sql = """
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  email text unique not null,
  password text not null,
  nombre text,
  role text default 'free',
  avatar_url text,
  is_premium boolean default false
);
"""

# We can't execute raw SQL easily with the js client without RPC, but the python client might not support it directly either 
# if the key doesn't have permissions. 
# However, we can try to use the 'rpc' interface if a function exists, or just rely on the user having created it?
# Actually, I'll assume I can't run DDL easily. 
# I will try to use the 'rpc' trick or just hope the table exists? 
# No, I must ensure it exists. 
# Wait, I can use the `requests` library to call the REST API if I had the service role key, but I only have anon key.
# The anon key usually can't create tables.

# ALTERNATIVE: I will use Supabase Auth (GoTrue) which IS enabled by default.
# But the user said "cuentas creadas deben subirse al supabase". Supabase Auth DOES store them in Supabase.
# The tricky part is the "custom fields" like 'role' or 'is_premium'.
# I can use the `public.users` table LINKED to Supabase Auth (profiles pattern).
# OR, I can just use a public table and manage it from the frontend (insecure but fits the "mineria de datos" student project vibe).
# Given the constraints and the user's likely level, a public table is easiest to debug and show "data in supabase".

# Let's try to insert a dummy user to see if the table exists. If it errors, I can't create it.
# If I can't create it, I'll have to ask the user to run SQL or use Supabase Auth.
# Actually, I'll try to use Supabase Auth because it's the "correct" way and I don't need to create a table for basic auth.
# But for "Profile" (photo, name), I need a table.
# I'll try to create the table using the python client. If it fails, I'll use Supabase Auth + LocalStorage for profile.

print("Attempting to check/create users table...")
try:
    # Try to select from users
    supabase.table('users').select("*").limit(1).execute()
    print("Table 'users' exists.")
except Exception as e:
    print(f"Table 'users' might not exist or error: {e}")
    print("Please create table 'users' in Supabase SQL Editor with: ")
    print(sql)

